<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Up for Free</name>
   <tag></tag>
   <elementGuidId>029640ed-195a-47ad-b926-ba1ee27ca1d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jfHeader-menuListLink.jfHeader-dynamicLink.jfHeader-signup-action.locale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='loginSignup']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75b8bc2b-a6e4-47b0-9b9b-df0d0869893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jfHeader-menuListLink jfHeader-dynamicLink jfHeader-signup-action locale</value>
      <webElementGuid>cb9969d5-3e99-40cf-99b1-bbf96eff4b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>signup</value>
      <webElementGuid>17d4ec63-e804-440e-a4bc-7939f619c5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5543164-8507-4a0d-9aab-bd06d1a6adc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>610324b0-8f98-4fad-8075-6d83e85bb109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up for Free</value>
      <webElementGuid>86f4ecc8-993b-4710-a6fe-efba7a602c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginSignup&quot;)/li[@class=&quot;jfHeader-menuListItem hasSubMenu signup-btn-wrapper&quot;]/a[@class=&quot;jfHeader-menuListLink jfHeader-dynamicLink jfHeader-signup-action locale&quot;]</value>
      <webElementGuid>396a5386-2e37-4add-9ba7-210dd423ce61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='loginSignup']/li[2]/a</value>
      <webElementGuid>4dadf8be-64a5-4f9d-9598-ec66325ca6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Sign Up for Free')])[2]</value>
      <webElementGuid>62c2c0e9-4ecd-40ec-aba9-a1de29af2ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>4b0e25c1-e59a-4055-a240-d15a636f9356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE 50%'])[2]/following::a[2]</value>
      <webElementGuid>7defaaa1-3ca0-4db3-9a61-a295b6c9dd21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Dialog'])[1]/preceding::a[1]</value>
      <webElementGuid>3705f820-5860-4b1e-97b3-00e89f37359e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EASIEST ONLINE FORM BUILDER'])[1]/preceding::a[1]</value>
      <webElementGuid>652abc31-7ee4-477f-be74-09b5a7d83fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/ul/li[2]/a</value>
      <webElementGuid>4a3c8faf-fcb7-42d5-be87-4a56c0a01e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Sign Up for Free' or . = 'Sign Up for Free')]</value>
      <webElementGuid>c0d82462-c266-4347-ad00-b3a33ba5d34c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
