<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up with Email</name>
   <tag></tag>
   <elementGuidId>11248381-9e55-4f13-a4c9-e72d7ee68859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup-with-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signup-with-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73c706d4-a680-4756-bd7f-3faa65bbd241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcl-button-em test_createAccount signup-with-email-button</value>
      <webElementGuid>eb29739b-6505-474d-801a-988f39dbaf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef9b3e65-8080-41e2-a39c-b4ed22377445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup-with-email</value>
      <webElementGuid>e2181623-708d-4cbb-89da-228fada2aa69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up with Email</value>
      <webElementGuid>53fadb42-7d0a-44ca-ac3e-06b7af9ae0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup-with-email&quot;)</value>
      <webElementGuid>299e4b52-0517-4289-b8ad-8cdff8d7b511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signup-with-email']</value>
      <webElementGuid>9e9d108f-6293-4075-b54c-eaf405e5a479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registrationForm']/button</value>
      <webElementGuid>e0598c52-ee0d-4ad0-b8cf-a1c538437f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>08effe41-eeab-431c-89b0-292e689fc676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with Facebook'])[1]/following::button[1]</value>
      <webElementGuid>4379feeb-37d2-4fb8-92b4-e0a58d45a1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::button[1]</value>
      <webElementGuid>e564b71a-b445-4db1-bdfb-77ec6d556c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up with Email']/parent::*</value>
      <webElementGuid>0018e01d-44ba-4248-bdaf-dcc0c3c0a464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>9c03da99-3bf1-41fd-919c-127d16a2e564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'signup-with-email' and (text() = 'Sign up with Email' or . = 'Sign up with Email')]</value>
      <webElementGuid>0b0b3bfe-ff3e-4d90-b4da-7e3a84a10220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
