<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign up with Email</name>
   <tag></tag>
   <elementGuidId>11248381-9e55-4f13-a4c9-e72d7ee68859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup-with-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signup-with-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c69e914-edc6-4953-bfe2-179da674c192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcl-button-em test_createAccount signup-with-email-button</value>
      <webElementGuid>45b7bff1-acd5-4c22-90e8-379362e98a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f43ca1c3-566e-4dda-88b8-3e883b0c0bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup-with-email</value>
      <webElementGuid>cb88df42-3cf2-4751-9f75-86b0c62e89db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up with Email</value>
      <webElementGuid>cdb34266-4ad0-4b1f-9075-c371cfb53e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup-with-email&quot;)</value>
      <webElementGuid>178ca775-32c2-4f6e-96c2-83df63078fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signup-with-email']</value>
      <webElementGuid>f18ada76-fa06-4abc-96a3-3a5e584d11b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registrationForm']/button</value>
      <webElementGuid>c2156e87-958b-4c8c-9620-23ba5dbc8010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/following::button[1]</value>
      <webElementGuid>b3c001f1-6ffe-4341-9831-6dd4a9959227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with Facebook'])[1]/following::button[1]</value>
      <webElementGuid>3d49f2d1-b6c2-476e-b04a-4602479307b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::button[1]</value>
      <webElementGuid>20eeb6cc-e9ac-4db1-b15f-721552202b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign up with Email']/parent::*</value>
      <webElementGuid>5ea311fe-a0d6-49d5-a6df-57f84b370c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>808512a6-b6d0-40b9-933d-882bee92b15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'signup-with-email' and (text() = 'Sign up with Email' or . = 'Sign up with Email')]</value>
      <webElementGuid>bd360bbe-f568-4035-b176-82a034a0d8df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
