<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_confirmPass</name>
   <tag></tag>
   <elementGuidId>ae478275-f2b7-4bd1-bcef-7e5a61e19add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suPasswordConf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suPasswordConf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08bd2d05-52b8-4951-acad-ea8f5e2a01df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcl-inp forPassword </value>
      <webElementGuid>fa753cef-2211-432f-a6f7-bb6c427d1509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f7a5a177-c6c3-45a5-bfcd-6eb3a5ebaacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPass</value>
      <webElementGuid>660e57c9-b965-4893-bb01-cd89b36268b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suPasswordConf</value>
      <webElementGuid>3ed2482f-4249-48aa-8cc2-a0ee695f8be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suPasswordConf&quot;)</value>
      <webElementGuid>5775702e-cd18-49c2-a5d0-a7dded299273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suPasswordConf']</value>
      <webElementGuid>841357b6-3749-412d-b297-15f9835430da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordConfField']/input</value>
      <webElementGuid>0fa88ee8-c6c4-40d5-9c0e-ad7d644d06e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>1eddf03b-7a09-4080-85e7-ee313188ca41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmPass' and @id = 'suPasswordConf']</value>
      <webElementGuid>f98beb37-417d-4183-aef3-3d233535d8af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
