<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_pass</name>
   <tag></tag>
   <elementGuidId>92b385b2-bfbf-4f3c-9b6a-c8c94bd16ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae132e0f-7adf-4d70-8df1-c3717f512127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcl-inp forPassword </value>
      <webElementGuid>1a1d56a0-a14a-4970-8d4e-32988f715f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3a75201e-bed3-427c-8091-616b5e45b92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pass</value>
      <webElementGuid>01d261b0-9abd-4146-a9c8-a3ad742b47ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suPassword</value>
      <webElementGuid>b61d24b3-9314-481d-b2d3-ce09767e6f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>88ff8a17-cbd9-4cfb-86fb-917796ad0fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suPassword&quot;)</value>
      <webElementGuid>395e1df8-815e-455c-a40f-0f07be48c362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suPassword']</value>
      <webElementGuid>a1c8dcbb-09ce-4570-94c2-6257369265b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordField']/input</value>
      <webElementGuid>cc4a5d89-8f8e-424d-a355-4c76dd74fafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>e4b5a547-7693-4f8f-80ab-f67d24c02606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pass' and @id = 'suPassword']</value>
      <webElementGuid>720b2e33-c5b2-4375-8e87-728443797870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
