<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_confirmPass</name>
   <tag></tag>
   <elementGuidId>ae478275-f2b7-4bd1-bcef-7e5a61e19add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suPasswordConf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suPasswordConf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74ad80b1-bf23-403e-bf56-6a9cf487942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xcl-inp forPassword </value>
      <webElementGuid>6130977f-8995-41a5-ae08-4bff3bf02dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a302816a-5cb7-490a-a358-a174b964b35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPass</value>
      <webElementGuid>d0902930-ea15-4508-99a8-c9b5201bae73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suPasswordConf</value>
      <webElementGuid>72b1ff38-518a-4ab9-b202-ae4a1b0b4509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suPasswordConf&quot;)</value>
      <webElementGuid>46de44be-be63-4ed5-9551-58e050006146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suPasswordConf']</value>
      <webElementGuid>3e05d276-0d1c-4454-996c-c76c10f68df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordConfField']/input</value>
      <webElementGuid>1414d0f1-5e9e-422c-b65a-c801ab6b0b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>d1b1c1c4-7974-4a54-b72c-34696e79c8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'confirmPass' and @id = 'suPasswordConf']</value>
      <webElementGuid>a08e5533-573f-438b-abd2-6a612cea4247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
