<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I agree to the Terms of Service and P_8aeb5a</name>
   <tag></tag>
   <elementGuidId>9d849cd9-46c2-4ce5-bde5-005643961c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.noTranslate.sacl-terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='termsField']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7ae4c2ec-5ab9-4bd5-8329-2f43772580e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noTranslate sacl-terms</value>
      <webElementGuid>415a32a0-bb8a-4f43-8780-c1a600287bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>ba0cb54b-1357-41dd-aee4-a7a3305c58c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I agree to the Terms of Service and Privacy Policy. </value>
      <webElementGuid>27c85e18-09b3-4758-9f08-9bdbf5a3b9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsField&quot;)/div[@class=&quot;xcl-terms-wr noTranslate&quot;]/label[@class=&quot;noTranslate sacl-terms&quot;]</value>
      <webElementGuid>c4fed6fe-957d-4409-87dc-a7a805eac6d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='termsField']/div/label</value>
      <webElementGuid>406409cf-949b-473a-a3e8-35f1fddb133b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[2]/following::label[1]</value>
      <webElementGuid>dc648dd1-dcd5-47fe-a6af-2d051ba83418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::label[1]</value>
      <webElementGuid>bf67e6d6-db1c-44a7-b74e-f9a411257611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I agree to the']/parent::*</value>
      <webElementGuid>577162bf-72ec-448b-acb9-9d3d0a23f506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>29f00b9e-97fe-4a28-a629-64c1628aca57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'I agree to the Terms of Service and Privacy Policy. ' or . = 'I agree to the Terms of Service and Privacy Policy. ')]</value>
      <webElementGuid>58ba86ee-952d-4be5-9832-119f385fe12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
