<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_I agree to the Terms of Service and P_8aeb5a</name>
   <tag></tag>
   <elementGuidId>9d849cd9-46c2-4ce5-bde5-005643961c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.noTranslate.sacl-terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='termsField']/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>aaa0caf4-f676-4170-9f77-119e3a3c7d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noTranslate sacl-terms</value>
      <webElementGuid>d7be1820-98dc-49a6-aa58-5ce4d67b07b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>5e549c79-6df2-4ee3-bfa5-4aae86e6c92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I agree to the Terms of Service and Privacy Policy. </value>
      <webElementGuid>afb376d0-444e-464f-85c6-66e11bb87f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsField&quot;)/div[@class=&quot;xcl-terms-wr noTranslate&quot;]/label[@class=&quot;noTranslate sacl-terms&quot;]</value>
      <webElementGuid>230211f4-5c10-4a99-b713-a998642d4661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='termsField']/div/label</value>
      <webElementGuid>346f357f-e724-4c9c-bf82-66e371e6f0ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[2]/following::label[1]</value>
      <webElementGuid>b61f0809-c258-4edf-9142-07114f441f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Password'])[1]/following::label[1]</value>
      <webElementGuid>d13638de-ae81-49dd-b753-5488984294cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='I agree to the']/parent::*</value>
      <webElementGuid>5a2f85f5-10ca-4510-a030-5ecccebfe0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label</value>
      <webElementGuid>aa9940e9-4a79-4115-a2d9-ea5f58bd5397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'I agree to the Terms of Service and Privacy Policy. ' or . = 'I agree to the Terms of Service and Privacy Policy. ')]</value>
      <webElementGuid>c5eb7c0a-48c6-4a59-9bfa-a7e89fad5851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
