<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Your password must include at least</name>
   <tag></tag>
   <elementGuidId>05bed69c-3449-405c-b3be-39ea32eb570f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hPass-reqs > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='passwordField']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>259ef992-30b3-4d2c-8017-2adc124c5ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your password must include at least</value>
      <webElementGuid>97e14b8e-a5c0-4cc2-b349-e1759352a71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordField&quot;)/div[@class=&quot;hPass-reqs&quot;]/p[1]</value>
      <webElementGuid>876ced17-5797-43e1-b9c9-ca2986144822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='passwordField']/div/p</value>
      <webElementGuid>42a56ef9-e012-4612-b593-7e96bffdda71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Password'])[1]/following::p[1]</value>
      <webElementGuid>09692a51-10db-4c70-aee4-497250c18892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::p[1]</value>
      <webElementGuid>49cfe0b4-99ac-4307-a779-1fefa8071e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms of Service'])[1]/preceding::p[1]</value>
      <webElementGuid>8477a977-e9f2-4889-9e70-1baa088ca960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your password must include at least']/parent::*</value>
      <webElementGuid>41bf813d-4b3a-47c0-aa47-50faeb8b1aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p</value>
      <webElementGuid>9ddcd769-84fa-4be4-96fb-4df093d1bfdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Your password must include at least' or . = 'Your password must include at least')]</value>
      <webElementGuid>83ef2cc1-be12-45e0-b127-56a384e10cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
